server :
  port : 9494
spring :
  datasource :
    url : jdbc:h2:mem:testUser
    username : sa
    password : 1234
  profiles :
    active :
      - UserJpa
  h2 :
    console :
      enabled : true
  application :
    name : rds-db